name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-test-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Backend Unit Tests
        run: |
          cd backend
          npm test

      - name: Run Frontend Unit Tests
        run: |
          cd frontend
          npm test

      - name: Merge dev into main
        if: ${{ success() }}
        uses: actions/github-script@v6
        with:
          script: |
            const sourceBranch = 'dev';
            const targetBranch = 'main';
            await github.rest.repos.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: targetBranch,
              head: sourceBranch,
            });

  build-test-deploy-main:
    needs: build-and-test-dev
    if: github.ref == 'refs/heads/dev' && success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fetch the main branch
        run: |
          git fetch origin main
          git checkout main

      - name: Build Docker Images
        run: |
          docker-compose build

      - name: Push Docker Images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker-compose push

      - name: Run Backend Unit Tests
        run: |
          cd backend
          npm install
          npm test

      - name: Run Frontend Unit Tests
        run: |
          cd frontend
          npm install
          npm test

      - name: Run E2E Tests
        run: |
          echo "Running E2E Tests..."
